services:

  jupyter:
    container_name: jupyter
    build: ./jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter/work:/home/jovyan/work
      - ./jupyter/conda/envs:/home/jovyan/.conda-envs
      - ./jupyter/conda/pkgs:/home/jovyan/.conda-pkgs
    environment:
      - NB_UID=1000 # Default
      - NVIDIA_VISIBLE_DEVICES=all
      - DOCKER_STACKS_JUPYTER_CMD=lab # Default is lab
    command: ./jupyter_start.sh
    restart: unless-stopped
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ngrok:
    container_name: ngrok
    image: ngrok/ngrok:latest
    network_mode: "host"
    volumes:
      - ./ngrok/ngrok.yml:/etc/ngrok.yml:ro
    command: start --config /etc/ngrok.yml --all --log=stdout
    restart: unless-stopped

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  data:
