services:

  jupyter:
    container_name: jupyter
    image: jupyter:latest
    build: ./jupyter
    ports:
      - 8888:8888
    volumes:
      - ./jupyter/work:/home/jovyan/work # jupyter work folder
      - ./jupyter/conda/envs:/home/jovyan/.conda-envs # conda envs
      - ./jupyter/conda/pkgs:/home/jovyan/.conda-pkgs # conda pkgs
      - ${HF_HOME}:/home/jovyan/huggingface # hf cache
      - ${TORCH_HOME}:/home/jovyan/pytorch # torch cache
    environment:
      - NB_UID=1000 # Default
      - NVIDIA_VISIBLE_DEVICES=all
      - DOCKER_STACKS_JUPYTER_CMD=lab # Default is lab
    command: ./jupyter_start.sh
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ngrok:
    container_name: ngrok
    image: ngrok/ngrok:latest
    network_mode: host
    volumes:
      - ./ngrok/ngrok.yml:/etc/ngrok.yml:ro
    command: start --config /etc/ngrok.yml --all --log=stdout
    restart: unless-stopped

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  nvitop:
    build: ./nvitop
    image: nvitop:latest
    container_name: nvitop
    pid: host
    entrypoint: [ "/venv/bin/python3", "-m", "nvitop", "--colorful"]
    stdin_open: true
    tty: true
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    ports:
      - 8088:80
    volumes:
      - ${FB_HOME}:/srv
      - ./fb/filebrowser.db:/database/filebrowser.db
      - ./fb/settings.json:/config/settings.json
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    restart: unless-stopped

volumes:
  data:
